name: reviewdog
on:
  pull_request:
    branches: [main]
    paths:
      - 'docs/**/*.md'

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: errata-ai/vale-action@reviewdog
        env:
          GITHUB_TOKEN: 
